# config for UNIONS catalogs
# contains file paths

phot_base_path: "/arc/projects/unions/catalogues/unions/GAaP_photometry/UNIONS5000/"
phot_input_file: "{tile}_SP_{bands}_photoz_ext.cat"
shear_input_file: "unions_shapepipe_cut_struc_2024_v1.5.4.fits"
run_label: "TESTP"
phot_output_label: "UNIONS5000"
shear_output_label: "SP_v1.5.4"
selection_label: flags_and_mags
do_phot_file: True
do_shear_file: True
do_main_file: True
do_txpipe_files: True
test_mode: True
parallel: False
use_batches: True
batch_size: 10000
n_workers: 8