# config for UNIONS catalogs
# contains file paths

phot_base_path: "/arc/projects/unions/catalogues/unions/GAaP_photometry/UNIONS5000/"
phot_input_file: "{tile}_SP_{bands}_photoz_ext.cat"
shear_input_file: "unions_shapepipe_cut_struc_2024_v1.5.4.fits"
run_label: "CATALOGP"
phot_output_label: "UNIONS5000_ALL"
shear_output_label: "SP_v1.5.4"
selection_label: all
do_phot_file: True
do_shear_file: False
do_main_file: False
do_txpipe_files: False
test_mode: False
parallel: True
use_batches: True
batch_size: 1000 #in tiles
n_workers: 16
input_shear_file: "/arc/projects/unions/lensing/matched_catalogs/CATALOGP_SHEAR_SP_v1.5.4_2025-05-14.h5"